include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  errors:
    cast_nullable_to_non_nullable: ignore
    inference_failure_on_function_invocation: ignore
    use_setters_to_change_properties: ignore
  exclude:
  - "**/*.mocks.dart"
  - "**/*.g.dart"
  - "**/app_localizations*.dart"
  - "**/firebase_options.dart"
linter:
  rules:
    public_member_api_docs: false
    require_trailing_commas: false
    lines_longer_than_80_chars: false
    always_use_package_imports: false
    prefer_relative_imports: true
    avoid_print: false